name: Run Spotify Script

on:
 workflow_dispatch:

jobs:
 run-script:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: '3.11'
     - name: Install dependencies
       run: pip install spotipy
     - name: Run script
       env:
         SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
         SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
         SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
       run: python spotifyTest.py
